//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupportLibrary.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add API Package.
        /// </summary>
        public static string AddAPIPackage {
            get {
                return ResourceManager.GetString("AddAPIPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Application.
        /// </summary>
        public static string AddApplication {
            get {
                return ResourceManager.GetString("AddApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Audible Book.
        /// </summary>
        public static string AddAudibleBook {
            get {
                return ResourceManager.GetString("AddAudibleBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Banner Notification.
        /// </summary>
        public static string AddBannerNotification {
            get {
                return ResourceManager.GetString("AddBannerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Chapter.
        /// </summary>
        public static string AddChapter {
            get {
                return ResourceManager.GetString("AddChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add FAQ.
        /// </summary>
        public static string AddFAQ {
            get {
                return ResourceManager.GetString("AddFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Glossary.
        /// </summary>
        public static string AddGlossary {
            get {
                return ResourceManager.GetString("AddGlossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Glossary Translation.
        /// </summary>
        public static string AddGlossaryTranslation {
            get {
                return ResourceManager.GetString("AddGlossaryTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Grammar.
        /// </summary>
        public static string AddGrammar {
            get {
                return ResourceManager.GetString("AddGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Chapter Title.
        /// </summary>
        public static string AdditionalChapterTitle {
            get {
                return ResourceManager.GetString("AdditionalChapterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Verse Title.
        /// </summary>
        public static string AdditionalVerseTitle {
            get {
                return ResourceManager.GetString("AdditionalVerseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Language.
        /// </summary>
        public static string AddLanguage {
            get {
                return ResourceManager.GetString("AddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Master Code.
        /// </summary>
        public static string AddMasterCode {
            get {
                return ResourceManager.GetString("AddMasterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Nuzul.
        /// </summary>
        public static string AddNuzul {
            get {
                return ResourceManager.GetString("AddNuzul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recitation.
        /// </summary>
        public static string AddRecitation {
            get {
                return ResourceManager.GetString("AddRecitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recitation Category.
        /// </summary>
        public static string AddRecitationCategory {
            get {
                return ResourceManager.GetString("AddRecitationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recitation Notification.
        /// </summary>
        public static string AddRecitationNotification {
            get {
                return ResourceManager.GetString("AddRecitationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recitation Type.
        /// </summary>
        public static string AddRecitationType {
            get {
                return ResourceManager.GetString("AddRecitationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reciter.
        /// </summary>
        public static string AddReciter {
            get {
                return ResourceManager.GetString("AddReciter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Special Content.
        /// </summary>
        public static string AddSpecialContent {
            get {
                return ResourceManager.GetString("AddSpecialContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recitation Sub Category .
        /// </summary>
        public static string AddSubRecitationCategory {
            get {
                return ResourceManager.GetString("AddSubRecitationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tajwid.
        /// </summary>
        public static string AddTajwid {
            get {
                return ResourceManager.GetString("AddTajwid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Translation.
        /// </summary>
        public static string AddTranslation {
            get {
                return ResourceManager.GetString("AddTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Translator.
        /// </summary>
        public static string AddTranslator {
            get {
                return ResourceManager.GetString("AddTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Verse.
        /// </summary>
        public static string AddVerse {
            get {
                return ResourceManager.GetString("AddVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Email.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Notifications.
        /// </summary>
        public static string AllNotifications {
            get {
                return ResourceManager.GetString("AllNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Quran.
        /// </summary>
        public static string AlQuran {
            get {
                return ResourceManager.GetString("AlQuran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Language Explaination.
        /// </summary>
        public static string AlternateLanguageExplanation {
            get {
                return ResourceManager.GetString("AlternateLanguageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Language Meaning.
        /// </summary>
        public static string AlternateLanguageMeaning {
            get {
                return ResourceManager.GetString("AlternateLanguageMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Language Chapter Title.
        /// </summary>
        public static string AlternativeLanguageChapterTitle {
            get {
                return ResourceManager.GetString("AlternativeLanguageChapterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Language Verse Title.
        /// </summary>
        public static string AlternativeLanguageVerseTitle {
            get {
                return ResourceManager.GetString("AlternativeLanguageVerseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجابة.
        /// </summary>
        public static string AnswerHD {
            get {
                return ResourceManager.GetString("AnswerHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Package.
        /// </summary>
        public static string APIPackage {
            get {
                return ResourceManager.GetString("APIPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Package Name.
        /// </summary>
        public static string APIPackageName {
            get {
                return ResourceManager.GetString("APIPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Packages.
        /// </summary>
        public static string APIPackages {
            get {
                return ResourceManager.GetString("APIPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Package Title.
        /// </summary>
        public static string APIPackageTitle {
            get {
                return ResourceManager.GetString("APIPackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible Book.
        /// </summary>
        public static string AudibleBook {
            get {
                return ResourceManager.GetString("AudibleBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible Books.
        /// </summary>
        public static string AudibleBooks {
            get {
                return ResourceManager.GetString("AudibleBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible Book Title.
        /// </summary>
        public static string AudibleBookTitle {
            get {
                return ResourceManager.GetString("AudibleBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Chapter.
        /// </summary>
        public static string BackToChapter {
            get {
                return ResourceManager.GetString("BackToChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Body Text.
        /// </summary>
        public static string BannerBodyText {
            get {
                return ResourceManager.GetString("BannerBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Image.
        /// </summary>
        public static string BannerImage {
            get {
                return ResourceManager.GetString("BannerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Notification.
        /// </summary>
        public static string BannerNotification {
            get {
                return ResourceManager.GetString("BannerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Notifications.
        /// </summary>
        public static string BannerNotifications {
            get {
                return ResourceManager.GetString("BannerNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner URl.
        /// </summary>
        public static string BannerURl {
            get {
                return ResourceManager.GetString("BannerURl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bookmark found..
        /// </summary>
        public static string BookMarkNotFound {
            get {
                return ResourceManager.GetString("BookMarkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Title.
        /// </summary>
        public static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string btnBackToList {
            get {
                return ResourceManager.GetString("btnBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string btnCreateNew {
            get {
                return ResourceManager.GetString("btnCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string btnDetails {
            get {
                return ResourceManager.GetString("btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string btnFilter {
            get {
                return ResourceManager.GetString("btnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha answer cannot be empty..
        /// </summary>
        public static string CaptchaRequired {
            get {
                return ResourceManager.GetString("CaptchaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ChangePasswordMsg {
            get {
                return ResourceManager.GetString("ChangePasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        public static string Chapter {
            get {
                return ResourceManager.GetString("Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Number.
        /// </summary>
        public static string ChapterNumber {
            get {
                return ResourceManager.GetString("ChapterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        public static string Chapters {
            get {
                return ResourceManager.GetString("Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Title.
        /// </summary>
        public static string ChapterTitle {
            get {
                return ResourceManager.GetString("ChapterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string CompareNewPassword {
            get {
                return ResourceManager.GetString("CompareNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Questions.
        /// </summary>
        public static string CompletedQuestions {
            get {
                return ResourceManager.GetString("CompletedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد الإعتماد لن تستطيع إجراء أي تعديلات على االأجوبة.
        /// </summary>
        public static string ConfirmationNotification {
            get {
                return ResourceManager.GetString("ConfirmationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ConfirmationPassword {
            get {
                return ResourceManager.GetString("ConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ConfirmDeleteMsg {
            get {
                return ResourceManager.GetString("ConfirmDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Required.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactNo.
        /// </summary>
        public static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactPerson.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate New Questionnaire.
        /// </summary>
        public static string CreateNewQuestionnaire {
            get {
                return ResourceManager.GetString("CreateNewQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Owner.
        /// </summary>
        public static string CreateOwner {
            get {
                return ResourceManager.GetString("CreateOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Current password field is required..
        /// </summary>
        public static string CurrentPasswordRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration In Seconds.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration In Seconds.
        /// </summary>
        public static string DurationInSeconds {
            get {
                return ResourceManager.GetString("DurationInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Invalid Login.
        /// </summary>
        public static string ErrorInvalidLogin {
            get {
                return ResourceManager.GetString("ErrorInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explaination.
        /// </summary>
        public static string Explaination {
            get {
                return ResourceManager.GetString("Explaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Title.
        /// </summary>
        public static string FAQTitle {
            get {
                return ResourceManager.GetString("FAQTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size In MB.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent to you, please check your email..
        /// </summary>
        public static string ForgotPasswordMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string ForgotPasswordTxt {
            get {
                return ResourceManager.GetString("ForgotPasswordTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossaries.
        /// </summary>
        public static string Glossaries {
            get {
                return ResourceManager.GetString("Glossaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary.
        /// </summary>
        public static string Glossary {
            get {
                return ResourceManager.GetString("Glossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary Title.
        /// </summary>
        public static string GlossaryTitle {
            get {
                return ResourceManager.GetString("GlossaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary Translation.
        /// </summary>
        public static string GlossaryTranslation {
            get {
                return ResourceManager.GetString("GlossaryTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary Translations.
        /// </summary>
        public static string GlossaryTranslations {
            get {
                return ResourceManager.GetString("GlossaryTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back to Dashboard.
        /// </summary>
        public static string GoBackToDashboard {
            get {
                return ResourceManager.GetString("GoBackToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back to Home.
        /// </summary>
        public static string GoBackToHome {
            get {
                return ResourceManager.GetString("GoBackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar.
        /// </summary>
        public static string Grammar {
            get {
                return ResourceManager.GetString("Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar List.
        /// </summary>
        public static string GrammarList {
            get {
                return ResourceManager.GetString("GrammarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the.
        /// </summary>
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL.
        /// </summary>
        public static string ImageURL {
            get {
                return ResourceManager.GetString("ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InValid Captcha.
        /// </summary>
        public static string IncorrectCaptcha {
            get {
                return ResourceManager.GetString("IncorrectCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiries.
        /// </summary>
        public static string Inquiries {
            get {
                return ResourceManager.GetString("Inquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email ID.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Answer.
        /// </summary>
        public static string IsAnswer {
            get {
                return ResourceManager.GetString("IsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Notification Sent.
        /// </summary>
        public static string IsNotificationSent {
            get {
                return ResourceManager.GetString("IsNotificationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juz.
        /// </summary>
        public static string Juz {
            get {
                return ResourceManager.GetString("Juz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Preference.
        /// </summary>
        public static string LanguagePreference {
            get {
                return ResourceManager.GetString("LanguagePreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Title.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Anywhere.
        /// </summary>
        public static string ListenAnywhere {
            get {
                return ResourceManager.GetString("ListenAnywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen wherever, whenever. Listen to your audiobooks with the Audible, or Kindle, app, and Echo too!.
        /// </summary>
        public static string ListenText {
            get {
                return ResourceManager.GetString("ListenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Button.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Content.
        /// </summary>
        public static string ManageContent {
            get {
                return ResourceManager.GetString("ManageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage News.
        /// </summary>
        public static string ManageNews {
            get {
                return ResourceManager.GetString("ManageNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Code.
        /// </summary>
        public static string MasterCode {
            get {
                return ResourceManager.GetString("MasterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Codes.
        /// </summary>
        public static string MasterCodes {
            get {
                return ResourceManager.GetString("MasterCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Code Title.
        /// </summary>
        public static string MasterCodeTitle {
            get {
                return ResourceManager.GetString("MasterCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        public static string Meaning {
            get {
                return ResourceManager.GetString("Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string MenuChangePassword {
            get {
                return ResourceManager.GetString("MenuChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string MenuContent {
            get {
                return ResourceManager.GetString("MenuContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string MenuCountry {
            get {
                return ResourceManager.GetString("MenuCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string MenuFAQ {
            get {
                return ResourceManager.GetString("MenuFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required.
        /// </summary>
        public static string MessageIsRequired {
            get {
                return ResourceManager.GetString("MessageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile is required.
        /// </summary>
        public static string MobileRequired {
            get {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        public static string ModifiedOn {
            get {
                return ResourceManager.GetString("ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mufassirs.
        /// </summary>
        public static string Mufassirs {
            get {
                return ResourceManager.GetString("Mufassirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bookmark.
        /// </summary>
        public static string MyBookmark {
            get {
                return ResourceManager.GetString("MyBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New password field is required..
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No strings attached.
        /// </summary>
        public static string NoStringsAttached {
            get {
                return ResourceManager.GetString("NoStringsAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel anytime, without hassles. You’ll also get our Great Listen Guarantee– exchange a book that didn’t meet your expectations..
        /// </summary>
        public static string NoStringsAttachedText {
            get {
                return ResourceManager.GetString("NoStringsAttachedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not an allowed file type.
        /// </summary>
        public static string NotAllowedFileType {
            get {
                return ResourceManager.GetString("NotAllowedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Frequency.
        /// </summary>
        public static string NotificationFrequency {
            get {
                return ResourceManager.GetString("NotificationFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Name Ar.
        /// </summary>
        public static string NotificationNameAr {
            get {
                return ResourceManager.GetString("NotificationNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Name Arabic.
        /// </summary>
        public static string NotificationNameArabic {
            get {
                return ResourceManager.GetString("NotificationNameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Name En.
        /// </summary>
        public static string NotificationNameEn {
            get {
                return ResourceManager.GetString("NotificationNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Name English.
        /// </summary>
        public static string NotificationNameEnglish {
            get {
                return ResourceManager.GetString("NotificationNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type.
        /// </summary>
        public static string NotificationType {
            get {
                return ResourceManager.GetString("NotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type Title.
        /// </summary>
        public static string NotificationTypeTitle {
            get {
                return ResourceManager.GetString("NotificationTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuzul.
        /// </summary>
        public static string Nuzul {
            get {
                return ResourceManager.GetString("Nuzul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuzul List.
        /// </summary>
        public static string NuzulList {
            get {
                return ResourceManager.GetString("NuzulList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner E-Mail.
        /// </summary>
        public static string OwnerEMail {
            get {
                return ResourceManager.GetString("OwnerEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page no :.
        /// </summary>
        public static string PageNo {
            get {
                return ResourceManager.GetString("PageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length Error.
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length Info.
        /// </summary>
        public static string PasswordLengthInfo {
            get {
                return ResourceManager.GetString("PasswordLengthInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords Do Not Match.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous bookmarks.
        /// </summary>
        public static string PreviousBookMark {
            get {
                return ResourceManager.GetString("PreviousBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of enquiry is required.
        /// </summary>
        public static string PurposeOfEnquiryIsRequired {
            get {
                return ResourceManager.GetString("PurposeOfEnquiryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links:.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation.
        /// </summary>
        public static string Recitation {
            get {
                return ResourceManager.GetString("Recitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Categories.
        /// </summary>
        public static string RecitationCategories {
            get {
                return ResourceManager.GetString("RecitationCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Category.
        /// </summary>
        public static string RecitationCategory {
            get {
                return ResourceManager.GetString("RecitationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Category Name.
        /// </summary>
        public static string RecitationCategoryName {
            get {
                return ResourceManager.GetString("RecitationCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation File.
        /// </summary>
        public static string RecitationFile {
            get {
                return ResourceManager.GetString("RecitationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitations.
        /// </summary>
        public static string Recitations {
            get {
                return ResourceManager.GetString("Recitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Size In MB.
        /// </summary>
        public static string RecitationSizeInMB {
            get {
                return ResourceManager.GetString("RecitationSizeInMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Sub Categories.
        /// </summary>
        public static string RecitationSubCategories {
            get {
                return ResourceManager.GetString("RecitationSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Sub Category.
        /// </summary>
        public static string RecitationSubCategory {
            get {
                return ResourceManager.GetString("RecitationSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Sub Category Name.
        /// </summary>
        public static string RecitationSubCategoryName {
            get {
                return ResourceManager.GetString("RecitationSubCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Type.
        /// </summary>
        public static string RecitationType {
            get {
                return ResourceManager.GetString("RecitationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Types.
        /// </summary>
        public static string RecitationTypes {
            get {
                return ResourceManager.GetString("RecitationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation Type Title.
        /// </summary>
        public static string RecitationTypeTitle {
            get {
                return ResourceManager.GetString("RecitationTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitation URL.
        /// </summary>
        public static string RecitationURL {
            get {
                return ResourceManager.GetString("RecitationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciter.
        /// </summary>
        public static string Reciter {
            get {
                return ResourceManager.GetString("Reciter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciters.
        /// </summary>
        public static string Reciters {
            get {
                return ResourceManager.GetString("Reciters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciter Title.
        /// </summary>
        public static string ReciterTitle {
            get {
                return ResourceManager.GetString("ReciterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register As New User.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Count.
        /// </summary>
        public static string RepeatCount {
            get {
                return ResourceManager.GetString("RepeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetSession {
            get {
                return ResourceManager.GetString("ResetSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revelation.
        /// </summary>
        public static string Revelation {
            get {
                return ResourceManager.GetString("Revelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results For.
        /// </summary>
        public static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Book.
        /// </summary>
        public static string SelectBook {
            get {
                return ResourceManager.GetString("SelectBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Book.
        /// </summary>
        public static string SelectedBook {
            get {
                return ResourceManager.GetString("SelectedBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Notification.
        /// </summary>
        public static string SelectNotification {
            get {
                return ResourceManager.GetString("SelectNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Recitation by File.
        /// </summary>
        public static string SelectRecitationByFile {
            get {
                return ResourceManager.GetString("SelectRecitationByFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Recitation by System.
        /// </summary>
        public static string SelectRecitationBySystem {
            get {
                return ResourceManager.GetString("SelectRecitationBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Recitation Type.
        /// </summary>
        public static string SelectRecitationType {
            get {
                return ResourceManager.GetString("SelectRecitationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reciter.
        /// </summary>
        public static string SelectReciter {
            get {
                return ResourceManager.GetString("SelectReciter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sub Category.
        /// </summary>
        public static string SelectSubCategory {
            get {
                return ResourceManager.GetString("SelectSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Translator.
        /// </summary>
        public static string SelectTranslator {
            get {
                return ResourceManager.GetString("SelectTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Verse.
        /// </summary>
        public static string SelectVerse {
            get {
                return ResourceManager.GetString("SelectVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Push Notification.
        /// </summary>
        public static string SendPushNotification {
            get {
                return ResourceManager.GetString("SendPushNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string SetPasswordMsg {
            get {
                return ResourceManager.GetString("SetPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Content.
        /// </summary>
        public static string SpecialContent {
            get {
                return ResourceManager.GetString("SpecialContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Contents.
        /// </summary>
        public static string SpecialContents {
            get {
                return ResourceManager.GetString("SpecialContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Content Title.
        /// </summary>
        public static string SpecialContentTitle {
            get {
                return ResourceManager.GetString("SpecialContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Content Title Arabic.
        /// </summary>
        public static string SpecialContentTitleAr {
            get {
                return ResourceManager.GetString("SpecialContentTitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql DB Con String.
        /// </summary>
        public static string SqlDBConString {
            get {
                return ResourceManager.GetString("SqlDBConString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surahs.
        /// </summary>
        public static string Surahs {
            get {
                return ResourceManager.GetString("Surahs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between Reading and Listening.
        /// </summary>
        public static string SwitchBetween {
            get {
                return ResourceManager.GetString("SwitchBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you don&apos;t have to put a good book down. More than 70,000 Audible titles allow you to switch seamlessly between reading your Kindle version and listening, without losing your place, on Kindle app and Fire devices..
        /// </summary>
        public static string SwitchBetweenText {
            get {
                return ResourceManager.GetString("SwitchBetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tafseers.
        /// </summary>
        public static string Tafseers {
            get {
                return ResourceManager.GetString("Tafseers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajwid.
        /// </summary>
        public static string Tajwid {
            get {
                return ResourceManager.GetString("Tajwid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajwid List.
        /// </summary>
        public static string TajwidList {
            get {
                return ResourceManager.GetString("TajwidList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your Enquiry. We will respond back Shortly..
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb URL.
        /// </summary>
        public static string ThumbURL {
            get {
                return ResourceManager.GetString("ThumbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Interval.
        /// </summary>
        public static string TimeInterval {
            get {
                return ResourceManager.GetString("TimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today’s bookmarks.
        /// </summary>
        public static string TodaysBookMark {
            get {
                return ResourceManager.GetString("TodaysBookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items.
        /// </summary>
        public static string TotalItems {
            get {
                return ResourceManager.GetString("TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Verses.
        /// </summary>
        public static string TotalVerses {
            get {
                return ResourceManager.GetString("TotalVerses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranslationText.
        /// </summary>
        public static string TranslationText {
            get {
                return ResourceManager.GetString("TranslationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        public static string Translators {
            get {
                return ResourceManager.GetString("Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranslatorsName.
        /// </summary>
        public static string TranslatorsName {
            get {
                return ResourceManager.GetString("TranslatorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Change Password.
        /// </summary>
        public static string UnableToChangePassword {
            get {
                return ResourceManager.GetString("UnableToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Id.
        /// </summary>
        public static string UnifiedId {
            get {
                return ResourceManager.GetString("UnifiedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Banner Image.
        /// </summary>
        public static string UploadBannerImage {
            get {
                return ResourceManager.GetString("UploadBannerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadRecitationFile.
        /// </summary>
        public static string UploadRecitationFile {
            get {
                return ResourceManager.GetString("UploadRecitationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string UseAccount {
            get {
                return ResourceManager.GetString("UseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse.
        /// </summary>
        public static string Verse {
            get {
                return ResourceManager.GetString("Verse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse ID.
        /// </summary>
        public static string VerseID {
            get {
                return ResourceManager.GetString("VerseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse Number.
        /// </summary>
        public static string VerseNumber {
            get {
                return ResourceManager.GetString("VerseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse Recitation.
        /// </summary>
        public static string VerseRecitation {
            get {
                return ResourceManager.GetString("VerseRecitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verses.
        /// </summary>
        public static string Verses {
            get {
                return ResourceManager.GetString("Verses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verses Translation.
        /// </summary>
        public static string VersesTranslation {
            get {
                return ResourceManager.GetString("VersesTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse  Title.
        /// </summary>
        public static string VerseTitle {
            get {
                return ResourceManager.GetString("VerseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse Translation.
        /// </summary>
        public static string VerseTranslation {
            get {
                return ResourceManager.GetString("VerseTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string ViewAllBookmarks {
            get {
                return ResourceManager.GetString("ViewAllBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as.
        /// </summary>
        public static string YouLoggedinAs {
            get {
                return ResourceManager.GetString("YouLoggedinAs", resourceCulture);
            }
        }
    }
}
